### ISSUE TITLE
Harrison, you've embarrased yourself

### ISSUE THREAD

**Issue by ghost** [Sentdex/GANTheftAuto#15]
You must be ashamed of yourself. Shame on you for mentioning that garbage job that your wife works for. Shame on your wife for choosing that job. What a daft and useless job she has.

@Sentdex another thing, you are NOT an Engineer.
 You know nothing about engineering. Engineering means designing and building real mechanical and structural objects, like turbines and buildings. Engineering has nothing to so with daft liars who sit behind their keyboards and write code. They are not engineer's, they are worthless kids

**Comment by ashimdahal** [comment]
Who’s this douchebag now?
