### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by Aragroth** [Sentdex/GANTheftAuto#2]
Not mentioned  `tensorflow`  and  `tensorflow_addons`  for running `gtav_inference_demo.sh` as dependencies in requirements.txt

**Comment by daniel-kukiela** [comment]
Technically upsample is not a part of it, but we embedded a model. But you are right that we should mention these dependencies, and IMO we should do this in the readme.

**Comment by daniel-kukiela** [comment]
Ok, readme updated: https://github.com/Sentdex/GANTheftAuto/blob/main/readme.md#playable-demo
Thank you!
