### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by Mapuut** [Sentdex/GANTheftAuto#9]
Followed installation instructions step by step, these instructions to be exact

![image](https://user-images.githubusercontent.com/35892391/122678673-75953100-d1f0-11eb-9a90-bd5c927e4e94.png)

No errors during installation, running gtav_interface_demo.bat gives file not found error.
```
C:\Users\Martin\Desktop\ganTheftAuto\GANTheftAuto>scripts\gtav_inference_demo.bat

C:\Users\Martin\Desktop\ganTheftAuto\GANTheftAuto>python inference.py  --saved_model ./trained_models/gan_5_1_17.pt  --data gtav:./data/gtav/gtagan_2_sample  --inference_image_path ./data/gtav/2.png  --show_base_images True  --upsample_model ./trained_models/upsample---[_20]---[______3171]---[_____63420].h5
C:\Users\Martin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\__init__.py
Traceback (most recent call last):
  File "C:\Users\Martin\Desktop\ganTheftAuto\GANTheftAuto\inference.py", line 25, in <module>
    ctypes.cdll.LoadLibrary('caffe2_nvrtc.dll')
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
Seems that this workaround for windows in interface.py does not work anymore because of newer version of pyTorch, thats my guess.
![image](https://user-images.githubusercontent.com/35892391/122678845-1f74bd80-d1f1-11eb-86f5-7b0f970f221c.png)

I have windows 10, dedicated gpu with drivers installed and up to date. nvcuda.dll present in C:/Windows/system32
If I am being stupid please let me know and feel free to close this issue.

**Comment by Sentdex** [comment]
Daniel is our Windows expert :P, so maybe he can help. In the meantime, I would be curious if you downgraded if it really does solve the issue. Maybe try the current LTS pytorch version (1.8.1) instead of 1.9

**Comment by Mapuut** [comment]
> Daniel is our Windows expert :P, so maybe he can help. In the meantime, I would be curious if you downgraded if it really does solve the issue. Maybe try the current LTS pytorch version (1.8.1) instead of 1.9

Seems I guessed completely wrong, installed torch 1.8.1 and torchlight 0.9.1 and it didn't really change anything.

```
C:\Users\Martin\Desktop\ganTheftAuto\GANTheftAuto>scripts\gtav_inference_demo.bat

C:\Users\Martin\Desktop\ganTheftAuto\GANTheftAuto>python inference.py  --saved_model ./trained_models/gan_5_1_17.pt  --data gtav:./data/gtav/gtagan_2_sample  --inference_image_path ./data/gtav/2.png  --show_base_images True  --upsample_model ./trained_models/upsample---[_20]---[______3171]---[_____63420].h5
C:\Users\Martin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\__init__.py
1.8.1+cpu
Traceback (most recent call last):
  File "C:\Users\Martin\Desktop\ganTheftAuto\GANTheftAuto\inference.py", line 26, in <module>
    ctypes.cdll.LoadLibrary('caffe2_nvrtc.dll')
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Martin\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by Mapuut** [comment]
Looked at this pullrequest: https://github.com/Sentdex/GANTheftAuto/pull/8/commits/65f552d0ddfdbe76a252909a42d0f05b5a0e8701
Changing `torch -> torch==1.9.0+cu102` , `torchvision -> torchvision==0.10.0+cu102` and running `pip3 install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html` did the trick. It renders about 1 frame every 10 seconds, but that seems to be because of GPU not registering which is already me problem :>
![image](https://user-images.githubusercontent.com/35892391/122682489-4daec900-d202-11eb-8074-52d8be659e0d.png)
You can close issue

**Comment by daniel-kukiela** [comment]
Yes,. you were missing PyTorch probably? As for your current error, it looks like cuDNN is not installed properly. This is curious as PyTorch comes with required binaries and it should work.
I'll close it following your request, but feel free to re-open it if necessary.
